version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

    commands:
      - echo "Python version"
      - python --version

      - echo "Upgrade pip tools"
      - pip install --upgrade pip setuptools wheel

      - "pip install PyYAML==6.0 --only-binary=:all:"

      # Required dependencies
      - pip install requests
      - pip install dulwich

      # Main tools
      - pip install cfn-lint==0.87.10
      - pip install taskcat==0.9.52

  pre_build:
    commands:
      - echo "Running cfn-lint"
      - cfn-lint template/main.yaml

  build:
    commands:
      - echo "Running taskcat"
      - taskcat test run

artifacts:
  files:
    - '**/*'