version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

    commands:
      - echo "Python version"
      - python --version

      - python -m venv venv
      - source venv/bin/activate

      - pip install "setuptools<81"

      - pip install --upgrade pip wheel

      - "pip install PyYAML==6.0 --only-binary=:all:"

      - pip install cfn-lint==0.87.10

      - "pip install taskcat[all]"

  pre_build:
    commands:
      - source venv/bin/activate
      - cfn-lint template/main.yaml

  build:
    commands:
      - source venv/bin/activate
      - echo "Running taskcat"
      - taskcat test run

artifacts:
  files:
    - '**/*'